name: CI

on: push

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: europe-west3
  PROJECT_BASE_URL: https://qawareblog-2ixogl4y4q-ey.a.run.app/
  DOCKER_GAR_NAME: qawareblog-docker
  SERVICE_NAME: qawareblog
  DOCKER_GAR_URL: "${{ env.RUN_REGION }}-docker.pkg.dev"
  DOCKER_GAR_PATH: "${{ env.DOCKER_GAR_URL }}/{{ env.PROJECT_ID }}/{{ env.DOCKER_GAR_NAME}}"
  DOCKER_IMAGE_PATH: "${{ env.DOCKER_GAR_PATH }}/{{ env.SERVICE_NAME }}:{{ github.sha }}"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.1.0
        with:
          submodules: true

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: "0.117.0"
          extended: true

      - name: Build
        run: hugo -s . --config ./config.toml --minify --cleanDestinationDir

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: qaware/qaware.github.io
          publish_dir: ./public
          #keep_files: true
          user_name: fuchshuber
          user_email: josef.fuchshuber@qaware.de
          publish_branch: master
          cname: blog.qaware.de

      # Setup gcloud CLI
      - name: 'Setup Cloud Auth'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          credentials_json:  ${{ secrets.RUN_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1.0.1'
        with:
          project_id: $PROJECT_ID

      # Configure docker to use the gcloud command-line tool as a credential helper 
      - run: gcloud auth configure-docker
      
      # Build the Docker image for staging environment
      - name: Build
        run: docker build --build-arg BASE_URL=$PROECT_BASE_URL --tag $DOCKER_IMAGE_PATH .
        
      # Push the Docker image to Google Artifact Registry
      - name: Publish
        run: docker push $DOCKER_IMAGE_PATH
        
      # Deploy the Docker image to Google Cloud Run
      - name: Deploy
        run: gcloud components install beta && gcloud beta run deploy $SERVICE_NAME --quiet --image $DOCKER_IMAGE_PATH --project $PROJECT_ID --region $RUN_REGION --platform managed --allow-unauthenticated  
